import activitySeed from '../../data/seed/activity-sources.json'
import wasteSeed from '../../data/seed/abfall-pulheim-2026-brauweiler.json'
import recipeSeed from '../../data/seed/recipes-seed.json'
import sortingSeed from '../../data/seed/waste-sorting-pulheim.json'
import type {
  ActivitySuggestion,
  DashboardData,
  Family,
  FamilyLink,
  LinkCollection,
  NoteItem,
  NotificationDelivery,
  Recipe,
  RecipeIngredient,
  RecipeSuggestion,
  ShoppingList,
  WasteDistrict,
  WasteEvent,
  WasteSortingItem,
} from '../types'

const family: Family = {
  id: 'demo-family',
  name: 'Familie Klein',
  default_timezone: 'Europe/Berlin',
}

const demoId = (prefix: string, index: number) => `${prefix}-${String(index + 1).padStart(2, '0')}`

export const createDemoData = (): DashboardData => {
  const shoppingLists: ShoppingList[] = [
    { id: 'shopping-supermarkt', family_id: family.id, title: 'Supermarkt', store_type: 'supermarkt', archived: false },
    { id: 'shopping-drogerie', family_id: family.id, title: 'Drogerie', store_type: 'drogerie', archived: false },
  ]

  const recipes: Recipe[] = recipeSeed.recipes.map((recipe, index) => ({
    id: demoId('recipe', index),
    family_id: family.id,
    title: recipe.title,
    description: recipe.description,
    source_type: 'seed',
    source_url: null,
    is_vegetarian: recipe.is_vegetarian,
    difficulty: recipe.difficulty as Recipe['difficulty'],
    prep_minutes: recipe.prep_minutes,
    cook_minutes: recipe.cook_minutes,
    servings: recipe.servings,
    tags: recipe.tags,
    visibility: 'family',
    status: 'active',
    created_by: null,
  }))

  const recipeIngredients: RecipeIngredient[] = recipeSeed.recipes.flatMap((recipe, recipeIndex) =>
    recipe.ingredients.map((ingredient, ingredientIndex) => ({
      id: demoId(`ingredient-${recipeIndex}`, ingredientIndex),
      recipe_id: demoId('recipe', recipeIndex),
      name: ingredient.name,
      quantity: ingredient.quantity,
      unit: ingredient.unit,
      note: null,
      shopping_category: ingredient.shopping_category,
      optional: false,
      sort_order: ingredientIndex + 1,
    })),
  )

  const wasteDistrict: WasteDistrict = {
    id: 'waste-district-demo',
    municipality: wasteSeed.district.municipality,
    district_name: wasteSeed.district.district_name,
    source_label: wasteSeed.district.source_label,
    source_checked_at: wasteSeed.district.source_checked_at,
    active: true,
  }

  const categoryIds = new Map(sortingSeed.categories.map((category, index) => [category.name, demoId('sorting-category', index)]))

  return {
    family,
    memberships: [
      {
        family_id: family.id,
        user_id: 'demo-user',
        role: 'admin',
        display_name: 'Robin',
        active: true,
        family,
      },
    ],
    events: [
      {
        id: 'event-demo-1',
        family_id: family.id,
        calendar_id: null,
        title: 'Familienrunde',
        starts_at: '2026-06-08T17:30:00.000Z',
        ends_at: '2026-06-08T18:00:00.000Z',
        all_day: false,
        recurrence_rule: null,
        category: 'Familie',
        location: 'Küche',
        notes: 'Kurz Wochenplanung, Einkauf und Termine sortieren.',
        is_important: true,
        notify_family: false,
        created_by: 'demo-user',
      },
      {
        id: 'event-demo-2',
        family_id: family.id,
        calendar_id: null,
        title: 'Sporttasche packen',
        starts_at: '2026-06-09T15:00:00.000Z',
        ends_at: null,
        all_day: false,
        recurrence_rule: null,
        category: 'Freizeit',
        location: null,
        notes: null,
        is_important: false,
        notify_family: false,
        created_by: 'demo-user',
      },
      {
        id: 'event-demo-3',
        family_id: family.id,
        calendar_id: null,
        title: 'Wochenendausflug offen',
        starts_at: '2026-06-13T09:00:00.000Z',
        ends_at: null,
        all_day: true,
        recurrence_rule: null,
        category: 'Aktivität',
        location: 'Pulheim/Köln',
        notes: null,
        is_important: false,
        notify_family: false,
        created_by: 'demo-user',
      },
    ],
    tasks: [
      {
        id: 'task-demo-1',
        family_id: family.id,
        title: 'Einkauf für die Woche prüfen',
        description: 'Rezepte und Standardartikel zusammenführen.',
        status: 'today',
        due_at: '2026-06-08T18:00:00.000Z',
        assigned_to: null,
        category: 'Einkauf',
        recurrence_rule: null,
        linked_event_id: null,
        is_important: true,
        notify_family: true,
        created_by: 'demo-user',
      },
      {
        id: 'task-demo-2',
        family_id: family.id,
        title: 'Mülltonnen rausstellen',
        description: 'Nächste Abholung beachten.',
        status: 'open',
        due_at: '2026-06-08T20:00:00.000Z',
        assigned_to: null,
        category: 'Abfall',
        recurrence_rule: null,
        linked_event_id: null,
        is_important: false,
        notify_family: false,
        created_by: 'demo-user',
      },
    ],
    shoppingLists,
    shoppingItems: [
      {
        id: 'item-demo-1',
        list_id: 'shopping-supermarkt',
        title: 'Milch',
        quantity: '2',
        unit: 'l',
        category: 'Kühlregal',
        source_label: null,
        checked: false,
        added_by: 'demo-user',
        checked_by: null,
        sort_order: 1,
      },
      {
        id: 'item-demo-2',
        list_id: 'shopping-supermarkt',
        title: 'Kartoffeln',
        quantity: '1',
        unit: 'kg',
        category: 'Gemüse',
        source_label: null,
        checked: false,
        added_by: 'demo-user',
        checked_by: null,
        sort_order: 2,
      },
      {
        id: 'item-demo-3',
        list_id: 'shopping-drogerie',
        title: 'Zahnpasta',
        quantity: '1',
        unit: 'Tube',
        category: 'Bad',
        source_label: null,
        checked: false,
        added_by: 'demo-user',
        checked_by: null,
        sort_order: 1,
      },
    ],
    linkCollections: [
      { id: 'links-alltag', family_id: family.id, title: 'Alltag', sort_order: 1 },
      { id: 'links-freizeit', family_id: family.id, title: 'Freizeit', sort_order: 2 },
    ] satisfies LinkCollection[],
    links: [
      {
        id: 'link-demo-1',
        collection_id: 'links-alltag',
        title: 'Stadt Pulheim',
        url: 'https://www.pulheim.de/',
        description: 'Kommunale Informationen',
        favorite: true,
        visible_to: null,
        is_important: false,
        notify_family: false,
      },
      {
        id: 'link-demo-2',
        collection_id: 'links-alltag',
        title: 'Wetter',
        url: 'https://www.dwd.de/',
        description: 'Wetter und Warnlage',
        favorite: true,
        visible_to: null,
        is_important: false,
        notify_family: false,
      },
    ] satisfies FamilyLink[],
    notes: [
      {
        id: 'note-demo-1',
        family_id: family.id,
        title: 'Notfallzettel prüfen',
        body: 'Sensible Daten erst nach Datenschutzentscheidung eintragen. Diese Demo zeigt nur die Struktur.',
        category: 'Sicherheit',
        visibility: 'adults',
        is_important: true,
        notify_family: false,
        updated_by: 'demo-user',
      },
    ] satisfies NoteItem[],
    wasteDistricts: [wasteDistrict],
    wasteEvents: wasteSeed.events.map((event, index) => ({
      id: demoId('waste', index),
      district_id: wasteDistrict.id,
      date: event.date,
      waste_type: event.waste_type as WasteEvent['waste_type'],
      title: event.title,
      location: null,
      starts_at: null,
      ends_at: null,
      source_id: null,
      source_event_uid: `${event.date}-${event.waste_type}`,
      notes: null,
    })),
    wasteSortingItems: sortingSeed.items.map((item, index) => ({
      id: demoId('sorting', index),
      category_id: categoryIds.get(item.category_name) ?? 'sorting-category',
      category_name: item.category_name,
      term: item.term,
      aliases: item.aliases,
      description: item.description,
      allowed: item.allowed,
      warning: item.warning,
      source_note: item.source_note,
    })) satisfies WasteSortingItem[],
    recipes,
    recipeIngredients,
    recipeSuggestions: recipes.slice(0, 5).map((recipe, index) => ({
      id: demoId('suggestion', index),
      family_id: family.id,
      recipe_id: recipe.id,
      suggestion_week: '2026-W24',
      rank: index + 1,
      reason: recipe.is_vegetarian ? 'Vegetarische Mindestabdeckung' : 'Abwechslung für die Woche',
      status: 'suggested',
      generated_by: 'seed-generator',
      recipe,
    })) satisfies RecipeSuggestion[],
    activitySuggestions: activitySeed.suggestions.map((activity, index) => ({
      id: demoId('activity', index),
      family_id: family.id,
      source_id: null,
      external_id: activity.external_id,
      title: activity.title,
      description: activity.description,
      starts_at: activity.starts_at,
      ends_at: activity.ends_at,
      location_name: activity.location_name,
      location_address: activity.location_address,
      distance_label: activity.distance_label,
      category: activity.category,
      family_score: activity.family_score,
      price_label: activity.price_label,
      age_label: activity.age_label,
      url: activity.url,
      image_url: activity.image_url,
      status: 'suggested',
      expires_at: null,
    })) satisfies ActivitySuggestion[],
    notificationDeliveries: [
      {
        id: 'delivery-demo-1',
        notification_id: 'notification-demo-1',
        user_id: 'demo-user',
        device_id: null,
        channel: 'in_app',
        status: 'pending',
        sent_at: '2026-06-08T08:15:00.000Z',
        read_at: null,
        error: null,
        notification: {
          id: 'notification-demo-1',
          family_id: family.id,
          created_by: 'demo-user',
          type: 'task',
          title: 'Neue wichtige Aufgabe',
          body: 'Einkauf für die Woche prüfen',
          target_type: 'task',
          target_id: 'task-demo-1',
          priority: 'urgent',
          created_at: '2026-06-08T08:15:00.000Z',
        },
      },
    ] satisfies NotificationDelivery[],
  }
}
